// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcitesstrngxvmlahxfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjaXRlc3N0cm5neHZtbGFoeGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDk3NTQsImV4cCI6MjA2OTUyNTc1NH0.doqtgUaIpuzZr8LVvlpCwXQT7wUIPn06bf9Zug8p29E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});